Add GLSK factors to flowbased results
farao-community/farao-core pull request #350
Opened 2020-10-22 14:46 UTC by terriervik

**Please check if the PR fulfills these requirements** *(please use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes)*
- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** *(Bug fix, feature, docs update, ...)*
Add GLSK factors to flowbased results:
  },
  "dataPostContingency" : [ ],
  "glskFactors" : {
    "FFR1F12 _generator" : 0.20391911,
    "BBE1B12 _generator" : 0.28446418,
    "BBE2B22 _generator" : 1.3545913E-8,
    "FFR2F22 _generator" : 9.710434E-9,
    "DDE5D52 _generator" : 0.4870327,
  }
}

2020-10-23 10:27 UTC, murgeyseb commented
The idea is good but the problem here is that you mix GLSK factors from all zones all together. You should seperate the different areas in the output.

2020-10-23 11:18 UTC, terriervik commented
@murgeyseb I've updated this, in order to dispay the areas.

2020-10-27 12:28 UTC, TheMaskedTurtle requested changes

2020-10-27 12:28 UTC, TheMaskedTurtle commented on data/flowbased-domain/src/test/resources/dataDomain.json
> +  "glskFactors" : null
Can you test with some existing factors ?

2020-10-27 13:44 UTC, closed without merging