Handle Crac synchronization with aliases in flowbased module
farao-community/farao-core pull request #357
Opened 2020-11-02 16:43 UTC by terriervik

**Please check if the PR fulfills these requirements** *(please use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes)*
- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem ?** *If so, link to this issue using `'#XXX'` and skip the rest*

**What kind of change does this PR introduce?** *(Bug fix, feature, docs update, ...)*

**What is the current behavior?** *(You can also link to an open issue here)*

**What is the new behavior (if this is a feature change)?**

**Does this PR introduce a breaking change?** *(What changes might users need to make in their application due to this PR?)*

**Other information**:

(if any of the questions/checkboxes don't apply, please delete them entirely)

2020-11-02 16:44 UTC, terriervik commented
@TheMaskedTurtle I've done this, is it what I had to do?

2020-11-03 08:40 UTC, murgeyseb requested changes

2020-11-03 08:40 UTC, murgeyseb commented on flowbased-computation/flowbased-computation-api/pom.xml
>          <!-- Runtime dependencies -->
Remove scope tag (compile is default) and move the dependance in compile dependencies area of the file

2020-11-03 09:22 UTC, murgeyseb approved these changes

2020-11-03 09:22 UTC, merged