WIP: Virtual hubs in loopflow computation
farao-community/farao-core pull request #393
Opened 2020-12-14 16:37 UTC by alexandrem-rte

**Please check if the PR fulfills these requirements** *(please use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes)*
- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** *(Bug fix, feature, docs update, ...)*
Feature: For each AssignedVirtualHub extension present in the network, a LinearGlsk will be created so that these virtual hubs are properly taken into account by the loopflow computation module.

**What is the current behavior?** *(You can also link to an open issue here)*
Currently, virtual hubs are not handled in the loopflow computation module.

**Other information**:
This merge request is based on:
- a refactoring of the refprog importer: https://github.com/farao-community/farao-core/pull/392
- a feature branch of farao-virtual-hubs repository: https://github.com/farao-community/farao-virtual-hubs/pull/4

(if any of the questions/checkboxes don't apply, please delete them entirely)

2020-12-18 17:04 UTC, baptsegu requested changes

2020-12-18 17:04 UTC, baptsegu commented on loopflow-computation/src/main/java/com/farao_community/farao/loopflow_computation/LoopFlowComputation.java
> +            glskMap.put(virtualHub.getId(), 1.0F);
The id of the GLSK map should be one of a generator or a load in the network.
Here, our sensitivityAnalysis will not be able to map the `virtualHub.getId()` on the network.

You could look here : https://github.com/farao-community/farao-core/blob/master/data/glsk/glsk-document-api/src/main/java/com/farao_community/farao/data/glsk/api/util/converters/GlskPointLinearGlskConverter.java

lines 95 to 102 -> We need to look in the network a generator which is located in the virtual Hub, and put the id of this generator in the glskMap.

If the AssignedVirtualHub is on a generator -> it's not gonna so difficult
If the AssignedVirtualHub is on a danglingLine -> it's gonna be more tricky

2021-01-04 10:40 UTC, alexandrem-rte commented on loopflow-computation/src/main/java/com/farao_community/farao/loopflow_computation/LoopFlowComputation.java
> +        generatorsWithVirtualHubs.forEach(generator -> handleVirtualHubGlsk(virtualHubGlsks, referenceExchangesFromVirtualHubs, generator));
i don't think it is possible to identify a dangling line or a generator matching with the description of the reference program, without using the virtual hub extension. Indeed, the reference program contains InArea and OutArea, whereas the Substation contain only a Country.

2021-01-05 16:34 UTC, baptsegu approved these changes

2021-01-11 08:34 UTC, baptsegu approved these changes
pair programming with @alexandrem-rte

2021-01-11 09:54 UTC, merged