User Story #16.3: Activate remedial actions only after a specific constraint
farao-community/farao-core pull request #488
Opened 2021-06-28 15:26 UTC by pet-mit

**Please check if the PR fulfills these requirements** *(please use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes)*
- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** *(Bug fix, feature, docs update, ...)*
Feature

**What is the current behavior?** *(You can also link to an open issue here)*
availability of remedial actions is assessed at the beginning of the search tree, regardless of the state of the network

**What is the new behavior (if this is a feature change)?**
availability of remedial actions is reassessed during the search tree, in order to be able to activate some remedial actions only after a specific constraint on an element

**Does this PR introduce a breaking change?** *(What changes might users need to make in their application due to this PR?)*
Some changes in the Crac API, with the creation of the OnFlowConstraint UsageRule implementation

2021-07-05 14:00 UTC, phiedw requested changes

2021-07-08 12:37 UTC, pet-mit commented on data/crac/crac-api/src/main/java/com/farao_community/farao/data/crac_api/Crac.java
>       * Gather all the range actions of a specified state with the specified usage method (available, forced or
done

2021-07-08 12:39 UTC, pet-mit commented on data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/OnFlowConstraintImpl.java
> +        return state.getInstant().equals(instant) ? UsageMethod.TO_BE_EVALUATED : UsageMethod.UNDEFINED;
unavailable would mean that the RA is definitely unavailable, no matter the other usage rules (UNAVAILABLE > other usage methods).
undefined means that this specific usage rule cannot say if the RA is available or not.

2021-07-08 12:41 UTC, pet-mit commented on ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/RangeActionFilter.java
> +     * If a range action has more priority (depending on the contents of leastPriorityRangeActions) then the other, then
corrected

2021-07-08 15:28 UTC, phiedw commented on data/crac/crac-impl/src/main/java/com/farao_community/farao/data/crac_impl/OnFlowConstraintImpl.java
> +        return state.getInstant().equals(instant) ? UsageMethod.TO_BE_EVALUATED : UsageMethod.UNDEFINED;
Indeed that makes sense :+1:

2021-07-08 15:50 UTC, phiedw approved these changes

2021-07-09 11:48 UTC, merged