adapt UCTE helpers depending on element sought (contingency vs. cnec vs. topo vs pst) + add Hvdc UCTE helper
farao-community/farao-core pull request #514
Opened 2021-09-06 13:01 UTC by baptsegu

2021-09-08 11:48 UTC, phiedw requested changes

2021-09-08 12:07 UTC, baptsegu commented on data/crac/crac-creation-util/src/main/java/com/farao_community/farao/data/crac_creation_util/iidm/IidmCnecElementHelper.java
> +        if (cnecElement instanceof Branch) {
it is an else if, thanks :)

2021-09-08 12:11 UTC, baptsegu commented on data/crac/crac-creation-util/src/main/java/com/farao_community/farao/data/crac_creation_util/iidm/IidmCnecElementHelper.java
> +                .findAny();
I agree.
This method 'interpretAsHalfLine()' is actually not used yet, i just put it in anticipation of the issue with the CIM Crac importer that we recently identified.

As we mostly work with UCTE networks, it's hard to know whether the impact is big or not. As discussed this morning, I propose that we postpone this question for the Cnec CIM Crac import :angel:.

If you prefer, i can remove this method in between.

2021-09-08 12:11 UTC, baptsegu commented on data/crac/crac-creation-util/src/main/java/com/farao_community/farao/data/crac_creation_util/ucte/UcteCnecElementHelper.java
> +    public String getIdInNetwork() {
removed

2021-09-08 12:12 UTC, baptsegu commented on data/crac/crac-creation-util/src/main/java/com/farao_community/farao/data/crac_creation_util/ucte/UcteCnecElementHelper.java
> +    protected void interpretWithNetworkAnalyzer(UcteNetworkAnalyzer networkHelper) {
renamed

2021-09-08 12:13 UTC, baptsegu commented on data/crac/crac-creation-util/src/main/java/com/farao_community/farao/data/crac_creation_util/ucte/UcteHvdcElementHelper.java
> +    public String getIdInNetwork() {
removed

2021-09-08 12:13 UTC, baptsegu commented on data/crac/crac-creation-util/src/main/java/com/farao_community/farao/data/crac_creation_util/ucte/UcteHvdcElementHelper.java
> +    protected void interpretWithNetworkAnalyzer(UcteNetworkAnalyzer networkHelper) {
renamed

2021-09-08 15:09 UTC, phiedw submitted a review, later dismissed

2021-09-08 15:10 UTC, phiedw commented on data/crac/crac-creation-util/src/main/java/com/farao_community/farao/data/crac_creation_util/iidm/IidmCnecElementHelper.java
> +                .findAny();
It's fine for now, we'll see when we work on the CIM import.

2021-09-17 11:36 UTC, pet-mit approved these changes

2021-09-17 11:37 UTC, merged