Create VoltageCnecs
farao-community/farao-core pull request #650
Opened 2022-08-18 15:00 UTC by pet-mit

**Please check if the PR fulfills these requirements** *(please use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes)*
- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem ?** *If so, link to this issue using `'#XXX'` and skip the rest*

**What kind of change does this PR introduce?** *(Bug fix, feature, docs update, ...)*

**What is the current behavior?** *(You can also link to an open issue here)*

**What is the new behavior (if this is a feature change)?**

**Does this PR introduce a breaking change?** *(What changes might users need to make in their application due to this PR?)*

**Other information**:

(if any of the questions/checkboxes don't apply, please delete them entirely)

2022-08-26 09:21 UTC, Godelaine requested changes

2022-08-29 08:28 UTC, pet-mit commented on data/crac-creation/crac-creator-cim/src/main/java/com/farao_community/farao/data/crac_creation/creator/cim/parameters/JsonVoltageCnecsCreationParameters.java
> +                    throw new IOException("Unexpected field in SwePreprocessorParameters: " + jsonParser.getCurrentName());
wrong copy / paste :p

2022-08-29 08:33 UTC, pet-mit commented on data/crac-creation/crac-creator-cim/src/main/java/com/farao_community/farao/data/crac_creation/creator/cim/parameters/JsonVoltageCnecsCreationParameters.java
> +    private static Unit stringToUnit(String string) {
but then we would have to write all deserializers here, even though we don't need them

2022-08-29 08:37 UTC, pet-mit commented on data/crac-creation/crac-creator-cim/src/main/java/com/farao_community/farao/data/crac_creation/creator/cim/crac_creator/CimCracCreator.java
> +            new VoltageCnecsCreator(cimCracCreationParameters.getVoltageCnecsCreationParameters(), creationContext, network).createAndAddCnecs();
added it

2022-08-29 12:19 UTC, Godelaine approved these changes

2022-08-29 12:19 UTC, merged