Reason per perimeter2
farao-community/farao-core pull request #710
Opened 2023-01-06 15:03 UTC by Godelaine

**Please check if the PR fulfills these requirements** *(please use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes)*
- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem ?** *If so, link to this issue using `'#XXX'` and skip the rest*

**What kind of change does this PR introduce?** *(Bug fix, feature, docs update, ...)*

**What is the current behavior?** *(You can also link to an open issue here)*

**What is the new behavior (if this is a feature change)?**

**Does this PR introduce a breaking change?** *(What changes might users need to make in their application due to this PR?)*

**Other information**:

(if any of the questions/checkboxes don't apply, please delete them entirely)

2023-01-11 14:58 UTC, Godelaine commented on ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/result/impl/SkippedOptimizationResultImpl.java
> + * License, v. 2.0. If a copy of the MPL was not distributed with this
TODO : clean and use default values for method héritées when necessary

2023-01-13 19:19 UTC, Godelaine commented on ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/result/impl/PreventiveAndCurativesRaoResultImpl.java
> +    @Override
why not use afterOptimizing :         return getPerimeterResult(OptimizationState.afterOptimizing(state.getInstant()), state).getSensitivityStatus(state);

2023-02-03 10:33 UTC, pet-mit requested changes

2023-02-07 13:57 UTC, pet-mit approved these changes

2023-02-07 13:57 UTC, merged