Second prev info in rao result
farao-community/farao-core pull request #711
Opened 2023-01-09 16:33 UTC by MartinBelthle

**Please check if the PR fulfills these requirements** *(please use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes)*
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem ?** *If so, link to this issue using `'#XXX'` and skip the rest*

No

**What kind of change does this PR introduce?** *(Bug fix, feature, docs update, ...)*

Feature

**What is the current behavior?** *(You can also link to an open issue here)*

You can only know if a rao went through 2nd preventive by reading the logs

**What is the new behavior (if this is a feature change)?**

You can access this information in the raoresult object

**Does this PR introduce a breaking change?** *(What changes might users need to make in their application due to this PR?)*

No

**Other information**:

(if any of the questions/checkboxes don't apply, please delete them entirely)

2023-01-10 10:45 UTC, phiedw requested changes
After discussing with Godelaine, we have come to the conclusion that it would be even better to have an enum to know whether we finished after the first preventive, run a second preventive and kept the 2P result, or run a second preventive and kept the 1P result

2023-01-10 13:33 UTC, pet-mit commented
> After discussing with Godelaine, we have come to the conclusion that it would be even better to have an enum to know whether we finished after the first preventive, run a second preventive and kept the 2P result, or run a second preventive and kept the 1P result

Or ran a 1P/2P but fell back to the initial situation

2023-01-24 13:44 UTC, phiedw requested changes

2023-01-24 13:44 UTC, phiedw commented on ra-optimisation/search-tree-rao/src/main/java/com/farao_community/farao/search_tree_rao/result/impl/PreventiveAndCurativesRaoResultImpl.java
> +                this.optimizationStepsExecuted.equals(OptimizationStepsExecuted.SECOND_PREVENTIVE_FELLBACK_TO_INITIAL_SITUATION)) {
and here too

2023-02-07 14:28 UTC, Godelaine commented on data/rao-result/rao-result-api/src/test/java/com/farao_community/farao/data/rao_result_api/OptimizationStepsExecutedTest.java
> +        assertFalse(optimizationStepsExecuted.isOverwritePossible(OptimizationStepsExecuted.SECOND_PREVENTIVE_FELLBACK_TO_FIRST_PREVENTIVE_SITUATION));
indentation (see other tests too)

2023-02-07 14:28 UTC, Godelaine commented on data/rao-result/rao-result-impl/src/test/java/com/farao_community/farao/data/rao_result_impl/RaoResultImplTest.java
> +    public void testRaoWentThroughSecondPrev() {
i don't understand the name of the test : FIRST_PREV... doesn't mean that rao went through 2P, does it ?

2023-02-07 14:28 UTC, Godelaine commented on data/rao-result/rao-result-json/src/main/java/com/farao_community/farao/data/rao_result_json/RaoResultJsonConstants.java
> +    public static final String FIRST_PREVENTIVE_ONLY = "The RAO went only through first preventive";
only went through

2023-02-08 08:41 UTC, Godelaine approved these changes

2023-02-08 08:56 UTC, merged